---
- name: configure a kvm server
  hosts: kvm_servers
  gather_facts: yes
  roles:
    - role: pxe_bridge
    - role: kvm
    - role: gnome
    - role: xrdp
    - role: dhcp
    - role: httpd
    - role: tftp-server
