---
- name: Define virtual machine from .xml template
  delegate_to: "{{ hypervisor }}"
  become: yes
  become_user: root
  virt:
    xml: "{{ lookup('template', vm_xml_template) }}"
    command: define
